# Generated by Django 3.2.3 on 2021-05-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=100)),
                ('Student_Id', models.CharField(max_length=50)),
                ('Student_Age', models.IntegerField(default=0)),
                ('Student_Dept', models.CharField(max_length=100)),
                ('Student_Cgpa', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_Name', models.CharField(max_length=100)),
                ('Teacher_Age', models.IntegerField(default=0)),
                ('Teacher_Dept', models.CharField(max_length=100)),
                ('Teacher_Salary', models.FloatField(default=0.0)),
                ('Teacher_Descation', models.TextField()),
            ],
        ),
    ]
